name: Build, Lint, Test, Docs Main

on:
  pull_request:
    branches:
      - main

jobs:
  dist:
    runs-on: ubuntu-latest

    services:
      ipfs:
        image: ipfs/kubo:latest
        ports:
          - 4001:4001
          - 4001:4001/udp
          - 8080:8080
          - 5001:5001
      minio:
        image: minio/minio
        ports:
          - 9000:9000
          - 9001:9001
        env:
          MINIO_ROOT_USER: minioadmin
          MINIO_ROOT_PASSWORD: minioadmin
        options: >-
          --name minio-server
          --health-cmd "curl -f http://localhost:9000/minio/health/live"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        volumes:
          - /tmp/data:/data

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Restore root node_modules from cache
        id: node-cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Run Lint and Dist
        run: |
          npm run lint
          npm run dist
